### ISSUE TITLE
PUT endpoint without trailing slash does nothing

### ISSUE THREAD

**Issue by karlb** [Layr-Labs/eigenda-proxy#88] opened 2024-08-14 09:49 UTC
The [OP alt-DA spec](https://specs.optimism.io/experimental/alt-da.html#da-server) requires
```
Request:
  POST /put
  Content-Type: application/octet-stream
  Body: <preimage_bytes>

Response:
  200 OK
  Content-Type: application/octet-stream
  Body: <hex_encoded_commitment>
```

The EigenDA proxy does not react on that URL and silently returns nothing, but it does work when appending a slash to the URL (which is not included in the spec).

```
karl@PVTY25Y2GX ~> curl -X POST http://127.0.0.1:3100/put --data foo -s | wc
       0       0       0
karl@PVTY25Y2GX ~> curl -X POST http://127.0.0.1:3100/put/ --data foo -s | wc
       0      13     187
```

Suggested changes:
* Respond with commitment at `/put`
* Respond with HTTP code 404 on unknown URLs

PS: The response does also not look hex-encoded, but that is a separate issue

**Comment by epociask** [comment] 2024-08-14 22:26
Hi @karlb , proxy is compatible with OP Alt-DA and we have a few integration [tests](https://github.com/Layr-Labs/eigenda-proxy/blob/main/e2e/server_test.go) with their client as well as an E2E [test](https://github.com/Layr-Labs/eigenda-proxy/blob/main/e2e/optimism_test.go) with a subset of an OP chain to verify these interactions. Additionally OP's example DA [server](https://github.com/ethereum-optimism/optimism/blob/develop/op-alt-da/daserver.go#L56) uses `/put/`. 

You're more than welcome to cut a PR with OP Stack specs repository directly if you feel like this regression needs remediation 😄

**Comment by karlb** [comment] 2024-08-25 14:57
See https://github.com/ethereum-optimism/optimism/issues/11499 for the follow-up in the optimism repo.

**Comment by samlaf** [comment] 2024-09-29 20:41
Reopening this issue since karl's PR https://github.com/ethereum-optimism/optimism/pull/12081 was just merged.
When we update our op-stack dependency to a release that includes his PR our tests will prob fail and hence catch this, but still opening here for visibility.

**Closed** 2024-10-12 09:18 UTC
